#ifndef HARDWARE_H
#define HARDWARE_H


#define PIN_BATTERY_SENSE A0
#define PIN_FAULT_LED D6
#define PIN_COMMS_LED D7

#define DEFAULT_BATTERY_VOLTAGE_MULTIPLIER 2 //nominal 50/50 voltage divider on battery voltage sense
#define DEFAULT_BATTERY_LOW_POWER_VOLTAGE 3.5
#define DEFAULT_BATTERY_FULL_POWER_VOLTAGE 4.0



#define DEFAULT_WEAPON_SPEED 0x7FFF

#define DEFAULT_HORN_FREQUENCY 200


#endif