#ifndef HARDWARE_H
#define HARDWARE_H

#define PIN_LEFT_JOYSTICK A1
#define PIN_RIGHT_JOYSTICK A2
#define PIN_LEFT_TRIGGER D9
#define PIN_RIGHT_TRIGGER D8
#define PIN_RIGHT_THUMB_SWITCH D3
#define PIN_WEAPON_TOGGLE_SWITCH D10
#define PIN_BATTERY_SENSE A0
#define PIN_FAULT_LED D6
#define PIN_COMMS_LED D7

#define DEFAULT_BATTERY_VOLTAGE_MULTIPLIER 2 //nominal 50/50 voltage divider on battery voltage sense
#define DEFAULT_BATTERY_LOW_POWER_VOLTAGE 3.5
#define DEFAULT_BATTERY_FULL_POWER_VOLTAGE 4.0



#define DEFAULT_WEAPON_SPEED 0x7FFF

#define DEFAULT_HORN_FREQUENCY 200


#endif